### ISSUE TITLE
No module named 'PyQt5'

### ISSUE THREAD

**Issue by jameswan** [QianyanTech/Image-Downloader#54]
C:\Users\James\Desktop\articles\Image-Downloader>pip install PyQt5
Collecting PyQt5
  Using cached PyQt5-5.15.9-cp37-abi3-win_amd64.whl (6.8 MB)
Collecting PyQt5-Qt5>=5.15.2
  Using cached PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (50.1 MB)
Collecting PyQt5-sip<13,>=12.11
  Using cached PyQt5_sip-12.11.1-cp39-cp39-win_amd64.whl (78 kB)
Installing collected packages: PyQt5-Qt5, PyQt5-sip, PyQt5
Successfully installed PyQt5-5.15.9 PyQt5-Qt5-5.15.2 PyQt5-sip-12.11.1

(yolo_classify) C:\Users\James\Desktop\articles\Image-Downloader>image_downloader_gui.py
Traceback (most recent call last):
  File "C:\Users\James\Desktop\articles\Image-Downloader\image_downloader_gui.py", line 7, in <module>
    from mainwindow import MainWindow
  File "C:\Users\James\Desktop\articles\Image-Downloader\mainwindow.py", line 5, in <module>
    from ui_mainwindow import Ui_MainWindow
  File "C:\Users\James\Desktop\articles\Image-Downloader\ui_mainwindow.py", line 11, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

**Comment by wallydomingo** [comment]
I am having the same issue.

**Comment by jameswan** [comment]
I got it to work.

C:\Users\James\Desktop\articles\Image-Downloader>**pip install PyQt5**
Collecting PyQt5
  Using cached PyQt5-5.15.9-cp37-abi3-win_amd64.whl (6.8 MB)
Collecting PyQt5-sip<13,>=12.11 (from PyQt5)
  Downloading PyQt5_sip-12.12.1-cp311-cp311-win_amd64.whl (78 kB)
     ---------------------------------------- 78.4/78.4 kB 4.3 MB/s eta 0:00:00
Collecting PyQt5-Qt5>=5.15.2 (from PyQt5)
  Using cached PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (50.1 MB)
Installing collected packages: PyQt5-Qt5, PyQt5-sip, PyQt5
Successfully installed PyQt5-5.15.9 PyQt5-Qt5-5.15.2 PyQt5-sip-12.12.1

C:\Users\James\Desktop\articles\Image-Downloader>**pip install chromedriver_autoinstaller**
Collecting chromedriver_autoinstaller
  Using cached chromedriver_autoinstaller-0.4.0-py3-none-any.whl (6.5 kB)
Installing collected packages: chromedriver_autoinstaller
Successfully installed chromedriver_autoinstaller-0.4.0

C:\Users\James\Desktop\articles\Image-Downloader>**python image_downloader_gui.py**
